language: ruby
sudo: false
rvm:
- 2.4.0
before_install: curl -OL --insecure https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip
  && unzip -d packer packer_0.12.3_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer
script: bundle exec thor packer:validate
notifications:
  slack:
    secure: ohPy5LBZD5NGfkkcLARb76330m8HtSDgNEAEljdkJ8NpCRaH0TFX/aVun8u6tOqdfXGH2wr/R+Aoghi0bbP+d+C5DOoIfa1nURPshkHF/2mZf2QuMrbQALPfv2l3FSlWuMfX9a8th3F1t/L3mj9qVKqYFWHlBOmHl6QrSpOKXFY=
